### ISSUE TITLE
练习题 4.9 勘误

### ISSUE THREAD

**Issue by asukaminato0721** [xueb96/C_O_D_5th#6]
[4.9的答案更正.pdf](https://github.com/xueb96/C_O_D_5th/files/4663356/4.9.pdf)

由某个大神吐槽了一份勘误，供参考。（这个答案看的我怀疑人生了）

**Comment by Fuann-Kinoko** [comment]
这份更正好像也有点问题，比如4.9.2 WB阶段用前半周期，ID阶段用后半周期，并没有冲突，2个nop足够了
